name: 'Self-update'
description: 'Automate the creation of update pull requests'
inputs:
  GITHUB_TOKEN: { "description": 'TODO', required: true }
  repository: { "description": 'The GitHub repository in the form owner/repo defaults to GITHUB_REPOSITORY', required: false }
  authorName: { "description": 'TODO', required: false }
  authorEmail: { "description": 'TODO', required: false }
  updateScript: { "description": 'TODO', required: true }
  applyUpdateScript: { "description": 'TODO', required: false }
  branchName: { "description": 'TODO', required: false }
  baseBranch: { "description": 'TODO', required: false }
  commitMessage: { "description": 'TODO', required: false }
  prTitle: { "description": 'TODO', required: false }
  prBody: { "description": 'TODO', required: false }

runs:
  using: 'node12'
  main: 'action.js'

branding:
  icon: 'tag'
  color: 'orange'
