name: 'Self-update'
description: 'Automate the creation of update pull requests'
inputs:
  GITHUB_TOKEN: { "description": 'Github API token (typically settings.GITHUB_TOKEN)', required: true }
  repository: { "description": 'The GitHub repository in the form owner/repo (defaults to GITHUB_REPOSITORY)', required: false }
  authorName: { "description": 'Author name (defaults to github actions bot)', required: false }
  authorEmail: { "description": 'Author email (defaults to github actions bot)', required: false }
  setupScript: { "description": "Script to prepare the update (changes from this script will not count)", required: true }
  updateScript: { "description": "Script to perform update", required: true }
  branchName: { "description": 'Branch name to use for PRs, will be force-pushed. Default `self-update`', required: false }
  baseBranch: { "description": 'Base branch for PR (default: checked out branch)', required: false }
  commitMessage: { "description": 'Commit message', required: false }
  prTitle: { "description": 'PR title', required: false }
  prBody: { "description": 'PR body', required: false }

outputs:
  pr_number:
    description: "The number of the PR that was created/updated"
  pr_url:
    description: "The URL to the PR that was created/updated"

runs:
  using: 'node12'
  main: 'action.js'

branding:
  icon: 'tag'
  color: 'orange'
